src/main/resources/application.yml
* cosmosdb/mongodb idle timeout limit fixed
* cosmosdb/mongodb min pool sizes fixed
=> Fix mongo idle timeout (#20)

src/main/java/it/gov/pagopa/reward/notification/repository/RewardsNotificationRepositoryExtendedImpl.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
* IDP-1106 findById optimize to be run on cosmosDB
* fixed unitTests
* extending coverage
=> feat: IDP-1106 findById optimize to be run on cosmosDB (#130)

src/main/java/it/gov/pagopa/reward/notification/service/commands/ops/DeleteInitiativeServiceImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify and info logs
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: info log and audit log fix for delate initiative

pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryNoControllerIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
**Description**
Added management 429 for idpay-reward-notification
**List of changes**
- Docker file
- Anchore
- Update dependencies
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> feat: IDP-1538-gestione-429-per-idpay-reward-notification

src/main/java/it/gov/pagopa/reward/notification/connector/rest/MerchantRestClientImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/notification/connector/rest/MerchantRestClientImplTest.java, src/test/resources/stub/merchant/mappings/merchantTooManyRequests.json
**Description**
The 429 thrown by the merchant microservice needed to be handled
**List of changes**
- Added retryWhen for get merchant rest client call
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: IDP-1678-Added retryWhen to restLevel getMerchant call and junit test

src/main/java/it/gov/pagopa/reward/notification/connector/rest/MerchantRestClientImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/notification/connector/rest/MerchantRestClientImplTest.java, src/test/resources/stub/merchant/mappings/merchantTooManyRequests.json
**Description**
The 429 thrown by the merchant microservice needed to be handled
**List of changes**
- Added retryWhen for get merchant rest client call
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: IDP 1678 5 lapi di forzatura generazione file dei rimborsi non funziona

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, .releaserc.json, CODEOWNERS, Dockerfile, helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
=> chore: release uat

.github/workflows/anchore.yml
=> chore: fix anchore skip step (#157)

Dockerfile
=> fix: IDP-1760 fix new critical CVE-2022-48174 (#161)

src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
=> feat: IDP-1765 selected API retryable

pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java, src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
=> feat: Release dev

helm/values.yaml, src/main/java/it/gov/pagopa/reward/notification/model/RewardIban.java, src/main/java/it/gov/pagopa/reward/notification/model/RewardNotificationRule.java, src/main/java/it/gov/pagopa/reward/notification/model/Rewards.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardIbanRepository.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardIbanRepositoryExtended.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardIbanRepositoryExtendedImpl.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardOrganizationImportsRepository.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardOrganizationImportsRepositoryExtended.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardOrganizationImportsRepositoryExtendedImpl.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsNotificationRepository.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsNotificationRepositoryExtended.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsNotificationRepositoryExtendedImpl.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsRepository.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsRepositoryExtended.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsRepositoryExtendedImpl.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsSuspendedUserRepository.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsSuspendedUserRepositoryExtended.java, src/main/java/it/gov/pagopa/reward/notification/repository/RewardsSuspendedUserRepositoryExtendedImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/commands/CommandsMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/notification/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/CommandsConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/notification/service/commands/ops/DeleteInitiativeServiceImplTest.java
This Pr includes:
IDP 1849
https://github.com/pagopa/idpay-reward-notification/pull/169
=> fix: Promote to UAT

.grype.yaml, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
=> fix: Idp 2016 fix CVE

.grype.yaml, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/DummySpringRepository.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
=> fix: Release dev

.github/CODEOWNERS, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/BaseIntegrationTest.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
=> chore: IDP-2102 configuring a single mongodb instance for all tests

Dockerfile, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportRewardNotificationCsvServiceIntegrationTest.java
=> chore: IDP-2115 fix CVE-2023-44487 on application-insight

.github/CODEOWNERS, Dockerfile, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportRewardNotificationCsvServiceIntegrationTest.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
=> chore: Release dev

pom.xml, src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/test/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImplTest.java
=> fix: IDP-2126 fix csv import error filename

pom.xml, src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/test/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImplTest.java
* fix import errors file name
* fix import errors file name
* bump version
* bump version
=> fix: IDP-2126 fix csv import error filename (#183)

src/main/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/BaseRewardNotificationHandlerService.java, src/main/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/BaseRewardNotificationThresholdBasedHandler.java, src/main/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/RewardNotificationTemporalHandlerServiceImpl.java, src/test/java/it/gov/pagopa/common/utils/TestUtils.java, src/test/java/it/gov/pagopa/reward/notification/connector/rest/MerchantRestClientImplTest.java, src/test/java/it/gov/pagopa/reward/notification/connector/rest/UserRestClientImplTest.java, src/test/java/it/gov/pagopa/reward/notification/dto/mapper/RewardNotificationExport2CsvMapperTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/CommandsConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/IbanOutcomeConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/IbanOutcomeRecoveryIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/BaseRewardResponseConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/RewardResponseConsumerConfigConcurrentTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/RewardResponseConsumerConfigTest.java, src/test/java/it/gov/pagopa/reward/notification/service/commands/ops/DeleteInitiativeServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportRewardNotificationCsvServiceIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/service/exports/detail/ExportDetailServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/BaseRewardNotificationThresholdHandlerTest.java, src/test/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/RewardNotificationBudgetExhaustedHandlerServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/RewardNotificationTemporalHandlerServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/rewards/evaluate/notify/RewardNotificationThresholdHandlerServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/test/fakers/RewardsNotificationFaker.java
=> fix: Idp 2132 fix reward merchant aggregation

src/main/java/it/gov/pagopa/reward/notification/dto/controller/detail/RewardNotificationDetailDTO.java, src/main/java/it/gov/pagopa/reward/notification/dto/mapper/RewardsNotificationMapper.java, src/main/java/it/gov/pagopa/reward/notification/dto/mapper/detail/RewardsNotification2DetailDTOMapper.java, src/main/java/it/gov/pagopa/reward/notification/dto/trx/TransactionDTO.java, src/main/java/it/gov/pagopa/reward/notification/model/RewardsNotification.java, src/test/java/it/gov/pagopa/reward/notification/dto/mapper/RewardsNotificationMapperTest.java, src/test/java/it/gov/pagopa/reward/notification/service/exports/detail/ExportDetailServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/test/fakers/RewardTransactionDTOFaker.java
Adapt API to get Merchant beneficiary type.
=> fix: IDP-1790-5-sp-dettaglio-refund-risponde-401

src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceTest.java
=> fix: Idp 2183 limit export file row rate production

pom.xml, src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java, src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/main/java/it/gov/pagopa/reward/notification/dto/controller/detail/RewardNotificationDetailDTO.java, src/main/java/it/gov/pagopa/reward/notification/dto/mapper/RewardsNotificationMapper.java, src/main/java/it/gov/pagopa/reward/notification/dto/mapper/detail/RewardsNotification2DetailDTOMapper.java, src/main/java/it/gov/pagopa/reward/notification/dto/trx/TransactionDTO.java, src/main/java/it/gov/pagopa/reward/notification/model/RewardsNotification.java, src/main/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/reward/notification/dto/mapper/RewardsNotificationMapperTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceTest.java, src/test/java/it/gov/pagopa/reward/notification/service/exports/detail/ExportDetailServiceImplTest.java, src/test/java/it/gov/pagopa/reward/notification/test/fakers/RewardTransactionDTOFaker.java
Promotion to UAT
- CVE fix -> [PR](https://github.com/pagopa/idpay-reward-notification/pull/188)
- fix limit export file row rate production -> [PR](https://github.com/pagopa/idpay-reward-notification/pull/190)
- fix config application insight -> [PR](https://github.com/pagopa/idpay-reward-notification/pull/191)
=> feat: Promote to UAT

pom.xml, src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionPayload.java, src/main/java/it/gov/pagopa/reward/notification/config/RewardNotificationErrorManagerConfig.java, src/main/java/it/gov/pagopa/reward/notification/config/ServiceExceptionConfig.java, src/main/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImpl.java, src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/main/java/it/gov/pagopa/reward/notification/exception/custom/WalletInvocationException.java, src/main/java/it/gov/pagopa/reward/notification/utils/Utils.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ServiceExceptionHandlerTest.java, src/test/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceTest.java
=> feat: IDP-2075 new error codes

pom.xml, src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionPayload.java, src/main/java/it/gov/pagopa/reward/notification/config/RewardNotificationErrorManagerConfig.java, src/main/java/it/gov/pagopa/reward/notification/config/ServiceExceptionConfig.java, src/main/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImpl.java, src/main/java/it/gov/pagopa/reward/notification/controller/NotificationControllerImpl.java, src/main/java/it/gov/pagopa/reward/notification/exception/custom/WalletInvocationException.java, src/main/java/it/gov/pagopa/reward/notification/utils/Utils.java, src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ServiceExceptionHandlerTest.java, src/test/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/csv/out/ExportInitiativeRewardsServiceTest.java
* feat: IDP-2075 new Error Codes
* bump version
* fixed unitTests
=> feat: IDP-2075 new error codes (#193)

src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ServiceExceptionHandlerTest.java
=> chore: fixed MemoryAppender append order

src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ServiceExceptionHandlerTest.java
* chore: fixed MemoryAppender append order
* chore: fixed MemoryAppender append order
=> chore: fixed MemoryAppender append order (#195)

Dockerfile, pom.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/reward/notification/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/connector/rest/UserRestClientImplTestIntegrated.java
=> fix: IDP-2196 fix Cve

src/test/java/it/gov/pagopa/reward/notification/event/consumer/CommandsConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/IbanOutcomeConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/IbanOutcomeRecoveryIntegrationTest.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/OrganizationFeedbackUploadEventConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/RefundRuleConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/BaseRewardResponseConsumerConfigTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/RewardResponseConsumerConfigConcurrentTestDeprecated.java, src/test/java/it/gov/pagopa/reward/notification/event/consumer/rewards/RewardResponseConsumerConfigTestDeprecated.java
Rename some tests that extends BaseIntegrationTest to reduce execution time.
=> fix: Review unit test

src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java, src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java, src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java, src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/reward/notification/config/KafkaConfiguration.java, src/main/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImpl.java, src/main/java/it/gov/pagopa/reward/notification/exception/custom/WalletInvocationException.java, src/main/java/it/gov/pagopa/reward/notification/service/RewardErrorNotifierService.java, src/main/java/it/gov/pagopa/reward/notification/service/RewardErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/commands/ops/DeleteInitiativeServiceImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/feedback/RewardNotificationFeedbackMediatorServiceImpl.java, src/main/java/it/gov/pagopa/reward/notification/service/rewards/RewardsMediatorServiceImpl.java, src/test/java/it/gov/pagopa/common/config/KafkaConfigurationTest.java, src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/reactive/web/exception/ServiceExceptionHandlerTest.java, src/test/java/it/gov/pagopa/reward/notification/connector/wallet/WalletRestClientImplTest.java, src/test/java/it/gov/pagopa/reward/notification/service/RewardErrorNotifierServiceImplTest.java
[IDP-2360](https://pagopa.atlassian.net/browse/IDP-2360)
[IDP-2360]: https://pagopa.atlassian.net/browse/IDP-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IPD-2360] Fix code smell and warnings

pom.xml
=> chore: Update pom version

Dockerfile
=> chore: update docker image runtime to fix cve (#219)

.grype.yaml, Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
=> chore: fix cve

.grype.yaml, Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-reward-notification/pull/224)
=> chore: Promote to Uat

.github/CODEOWNERS, Dockerfile, pom.xml
=> fix: CVE fix

.github/CODEOWNERS, Dockerfile, pom.xml
* amazoncorretto and aplicationinsights version change
* GHSA-4g8c-wm8x-jfhw fix
* Update CODEOWNERS
=> fix: CVE fix (#231)

Dockerfile, pom.xml
=> chore: [IDP-2676] jdk udpate to 21
